apiVersion: v1
kind: Service
metadata:
  name: test new one-system-entry
  namespace: test new one
spec:
  type: NodePort
  ports:
  - name: nginx-app
    port: 80
    targetPort: 80
  selector:
    app: test new one-system-entry