apiVersion: v1
kind: Service
metadata:
 labels:
   name: test new one-app-db
 name: test new one-app-db
 namespace: test new one
spec:
 type: NodePort
 ports:
 - name: mongo-db
   port: 27017
   targetPort: 27017
 selector:
   name: test new one-app-db