apiVersion: v1
kind: Service
metadata:
  name: test new one-telemetry
  labels:
    app: test new one-telemetry
  namespace: test new one  
spec:
  type: NodePort
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
  selector:
    app: test new one-telemetry