apiVersion: v1
kind: Service
metadata:
  name: test new one-app
  namespace: test new one
spec:
  type: NodePort
  ports:
  - name: node-app
    port: 3000
    targetPort: 3000
  selector:
    app: test new one-app